### ISSUE TITLE
Addon Architecture Review

### ISSUE THREAD

**Issue by gregjopa** [gregjopa/ember-power-select-form#1]
@cibernox - I'd like to get your feedback on this new ember-power-select addon I created. The README contains some details about the purpose of this addon and the architecture details. Checkout the example ember app in the tests/dummy directory to see this addon in action.

I know this addon is an edge case for ember-power-select. But the composition design pattern used with ember-power-select made it pretty easy to create. 

The following two things felt hacky to me when overriding the `selectOptions` component:
1. Triggering the onchange event - I did this by triggering the `select` event and passing through the transformed parameters. I wasn't sure how to pass the `dropdown` param so I just left it blank. https://github.com/gregjopa/ember-power-select-complex/blob/master/tests/dummy/app/components/select-options.js#L62
2. Closing the dropdown - I did this using the `opened` api option. I used `this.get('targetObject')` to get access to the main component from inside the `selectOptions` component. Is there a better way to refer to the parent component?

Any feedback you have would be greatly appreciated.

**Comment by cibernox** [comment]
This is quite and edge case, indeed. 
I'm genuinely astonished (but delighted) that you were able to stretch ember-power-select to this length :astonished: 

About your doubts:
1. Using the `select` action to trigger the `onchange` event is exactly the proper way to do it. Alternatively you could use `choose`, which is more or less equivalente to `select` + `close`. And precisely, you don't need to pass the `dropdown` to the action, because the action is a closure action that already has the [dropdown bound as first argument](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select.hbs#L26), for convenience. 
   However, closure actions should be invoked directly instead of with `sendAction` to work as expected. 
   Just replace `this.sendAction('submit', {}, params)` with `this.get('select').select(params)`.
2. As I mentioned, you can either use `this.get('select').choose` instead of `this.get('select').select` to both select & close, or you can also use `this.get('select').close()` to manually do it.

Another suggestions: 
- Add `ember-power-select-addon` to the list of keywords, so I can track meta-addons. Example: https://github.com/cibernox/ember-power-select-with-fallback/blob/master/package.json#L47
- `ember-power-select-complex` is not very descriptive of what the addon does, although I can't really suggest a better name. `ember-power-select-form`?

Again, I'm mind blown for this :+1:

**Comment by gregjopa** [comment]
@cibernox Thanks for your feedback. It's been very helpful. :+1:  I agree that this is a fun example of what can be done with extending `ember-power-select`.

I updated this addon to use `this.get('select')` for calling actions. I had to use `this.get('select').actions.choose(params)` vs. `this.get('select').choose(params)` to get it to work. The `actions` key had to be included.

I agree that the addon name was vague. I renamed it to `ember-power-select-form` (thanks for the suggestion!). I added some keywords and published it to npm.

My plan is to integrate this addon into my [ember-reporting-dashboard](https://github.com/gregjopa/ember-reporting-dashboard) app to better showcase the benefits of this component.

**Comment by gregjopa** [comment]
@cibernox I successfully updated this addon to use the latest and greatest version of ember-power-select in PR #2. I ran into one small problem. Previously I was using the following code to make items optionally dismissible:

``` hbs
{{#if opt.isDismissible}}
  <span role="button" 
    aria-label="remove element" 
    class="ember-power-select-multiple-remove-btn"
    onmousedown={{action select.actions.select (ember-power-select-build-selection opt selected multiple=true)}}>
    &times;
  </span>
{{/if}}
```

This approach no longer works. I updated this code to following but I'm not sure how to trigger the dismiss action:

``` hbs
{{#if opt.isDismissible}}
  <span role="button"
    aria-label="remove element"
    class="ember-power-select-multiple-remove-btn"
    data-selected-index={{idx}}>
    &times;
  </span>
{{/if}}
```

Is there a new action I need to call for this dismiss behavior?

**Comment by gregjopa** [comment]
@cibernox I got the dismiss behavior working. The dummy app now demos this functionality.

I just released ember-power-select-form@1.0.0. Thanks again for the awesome ember-power-select library!

**Comment by cibernox** [comment]
I'm going to add it to the list of addons.

**Comment by gregjopa** [comment]
Awesome!
